# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

sphinx:
  configuration: docs/conf.py
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
